-- AlterTable
ALTER TABLE "SKU" ADD COLUMN     "taxCodeId" INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE "SKU" ADD CONSTRAINT "SKU_taxCodeId_fkey" FOREIGN KEY ("taxCodeId") REFERENCES "TaxCode"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
