-- DropForeignKey
ALTER TABLE "GRN" DROP CONSTRAINT "GRN_vendorId_fkey";

-- AlterTable
ALTER TABLE "GRN" ALTER COLUMN "vendorId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "GRN" ADD CONSTRAINT "GRN_vendorId_fkey" FOREIGN KEY ("vendorId") REFERENCES "Vendor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
