-- CreateEnum
CREATE TYPE "RoleType" AS ENUM ('DOCTOR', 'NURSE', 'RECEPTIONIST', 'ADMIN', 'ACCOUNTANT', 'PHARMACIST', 'LAB_TECHNICIAN');

-- AlterTable
ALTER TABLE "Role" ADD COLUMN     "roleType" "RoleType" NOT NULL DEFAULT 'DOCTOR';
